### ISSUE TITLE
Theme doesn't work for Powercord

### ISSUE THREAD

**Issue by sfarmani** [SlippingGitty/surCord#1]
Theme doesn't seem to work for Powercord

I was able to make it work by editing the manifest.json file from `./src/_index.scss` to `./surCord.theme.css`.

Can there be a more permanent solution?

Windows 11
Canary
powercord
English

**Comment by SlippingGitty** [comment]
Thank you for your feedback! A friend issued a pull request which should fix this issue. Hopefully this is resolved.
