### ISSUE TITLE
Icon for the new section "Friend Requests" in User Settings

### ISSUE THREAD

**Issue by CJStyles123** [SlippingGitty/surCord#11]
recent Canary update introduced a new section called Friend Requests in the User Settings. I was wondering if an icon could be added to it.
![image](https://user-images.githubusercontent.com/90815473/177476257-c9d9376a-b90b-41f4-9ec6-0efe42815833.png)

**Comment by SlippingGitty** [comment]
![image](https://user-images.githubusercontent.com/76500838/177684626-4b9da0a6-96ab-4ba9-ad66-98860cf3a3f9.png)

An icon has been [added.](https://github.com/SlippingGitty/surCord/commit/bc9eed4a04db9d5ccdb4aacd2596999d28af21ce)
