### ISSUE TITLE
Altering the colour changes most things, but not all.

### ISSUE THREAD

**Issue by pozm** [SlippingGitty/surCord#12]
You can see it in the following locations:
- **Context menus**: if you put your cursor just outside of hover range or if you focus a submenu<details><summary>Image</summary>![image](https://user-images.githubusercontent.com/44528100/177802416-ee79babe-9cfa-4cc2-badf-6754af8922a4.png) </details>
- **Replying to a message**: if you try to reply to a message, the colour showing the selected message will be in the incorrect colour. <details><summary>Image</summary>![image](https://user-images.githubusercontent.com/44528100/177803008-e323f59d-d2f6-477e-a99d-cef748d38f4f.png)</details>
- **Check Boxes**: Checkboxes will remain blue when enabled<details><summary>Image</summary>![image](https://user-images.githubusercontent.com/44528100/177803305-96a64877-9eb8-420f-a326-0a5d3e21b51c.png)</details>
- **Radio selection**: Radios within context menus seem to only be blue.<details><summary>Image</summary>![image](https://user-images.githubusercontent.com/44528100/177804241-a80b481a-d959-4664-b168-b77e987e1242.png)</details>
- **Buttons hover**: Upon hovering over some buttons they go back to blue.<details><summary>Images</summary>![i](https://i.imgur.com/TDPk25J.gif) ![i](https://i.imgur.com/or1Wx1h.gif) ![i](https://i.imgur.com/DjJGNrY.gif) ![i](https://i.imgur.com/M4Spps0.gif) ![i](https://i.imgur.com/QV1TzR3.gif) ![i](https://i.imgur.com/9BD1JLG.gif) ![i](https://i.imgur.com/1GYs74O.gif) ![i](https://i.imgur.com/NQWwzUi.gif) ![i](https://i.imgur.com/0yDJfPr.gif) ![i](https://i.imgur.com/mEGeTSC.gif)</details>
- **Sliders**: Sliders seem to not change colour at all..<details><summary>Image</summary>![image](https://i.imgur.com/UqGWm4o.png)</details>
These are most of the locations which i could find within a reasonable time span, im sure there are more but obviously it will just take time to patch them all out.

**Comment by SlippingGitty** [comment]
I will begin to work on all of this, thank you for your feedback!

**Comment by pozm** [comment]
Looks awesome, great work! thanks for making a wonderful theme
