### ISSUE TITLE
Theme leaves a solid line through server banners

### ISSUE THREAD

**Issue by BritishBenji** [SlippingGitty/surCord#3]
As in the title, example shown below:

![image](https://user-images.githubusercontent.com/67644386/172497801-7b9e4cbf-61c8-4595-a5d2-0dd55b5ac2be.png)

Currently using:
Discord Canary 131204 (1ea62d4) 
Host 1.0.46 
Windows 10 64-Bit (10.0.19044)
Powercord v2 (92ceae9)

**Comment by SlippingGitty** [comment]
Thank you for bringing this to my attention. 

![image](https://user-images.githubusercontent.com/76500838/172523251-e0b939e7-3369-47bb-bd70-d7bb8ae7ddb2.png)

I hope that this is more your liking. I have pushed this change.

**Comment by BritishBenji** [comment]
That's perfect, thank you!
Sorry if it seemed like a petty change 😅

**Comment by ReeceTaylor512** [comment]
![image](https://github.com/SlippingGittys-Discord-Themes/surCord/assets/73254003/26960cee-03a0-4a6e-9bc8-eb852d86413f)

Sorry to be a pain but I also have this issue with this. (On the Tokyo Palette if it matters)
